### ISSUE TITLE
`su` command not respecting /etc/passwd

### ISSUE THREAD

**Issue by rkevin-arch** [evinism/homepage#12]
I stumbled onto your website and it's really cool! However, the `su` utility doesn't seem to respect `/etc/passwd`, even if I change it. After changing `/etc/passwd` and replacing root's md5 password hash to a known value (`password`), `su` still says the new password is incorrect. The original password for root still works even if `/etc/passwd` is changed. The screenshot below sort of shows this (the passwords aren't echoed, but you get the point). Of course, this is a minor issue that probably no one would care about, so feel free to ignore this.
![image](https://user-images.githubusercontent.com/5837628/88980570-db936580-d278-11ea-9148-b7bc12d17fe9.png)

**Comment by evinism** [comment]
👏 👏 👏 Excellent work, friend 👏 👏 👏 

Looks like it loads all users / passwords from `/etc/passwd` [only at startup](https://github.com/evinism/homepage/blob/96a53d49b3b2ff5a87cb2472e0b810f3b0e09cff/src/vm/os/os.ts#L52).

This would be an excellent attack vector given missing file permissions.

**Comment by evinism** [comment]
Fixed! I LOVE this attack vector.
